/* Generated By:JavaCC: Do not edit this line. ASParserConstants.java */
package com.flagstone.translate;

public interface ASParserConstants {

  int EOF = 0;
  int BOOLEAN_LITERAL = 8;
  int NULL_LITERAL = 9;
  int INTEGER_LITERAL = 10;
  int DECIMAL_LITERAL = 11;
  int HEX_LITERAL = 12;
  int FLOATING_POINT_LITERAL = 13;
  int EXPONENT = 14;
  int STRING_LITERAL = 15;
  int DOUBLE_QUOTE = 16;
  int SINGLE_QUOTE = 17;
  int ASSIGN = 18;
  int ASSIGN_ADD = 19;
  int ASSIGN_SUB = 20;
  int ASSIGN_MUL = 21;
  int ASSIGN_DIV = 22;
  int ASSIGN_MOD = 23;
  int ASSIGN_LSL = 24;
  int ASSIGN_ASR = 25;
  int ASSIGN_LSR = 26;
  int ASSIGN_AND = 27;
  int ASSIGN_OR = 28;
  int ASSIGN_XOR = 29;
  int LOGICAL_AND = 30;
  int LOGICAL_OR = 31;
  int LOGICAL_NOT = 32;
  int EQ = 33;
  int GT = 34;
  int LT = 35;
  int GTE = 36;
  int LTE = 37;
  int NE = 38;
  int BIT_AND = 39;
  int BIT_OR = 40;
  int BIT_XOR = 41;
  int BIT_NOT = 42;
  int LSL = 43;
  int LSR = 44;
  int ASR = 45;
  int PLUS = 46;
  int MINUS = 47;
  int MULTIPLY = 48;
  int DIVIDE = 49;
  int MOD = 50;
  int INC = 51;
  int DEC = 52;
  int IF = 53;
  int ELSE = 54;
  int WHILE = 55;
  int DO = 56;
  int FOR = 57;
  int IN = 58;
  int BREAK = 59;
  int CONTINUE = 60;
  int DELETE = 61;
  int INSTANCEOF = 62;
  int RETURN = 63;
  int WITH = 64;
  int NEW = 65;
  int FUNCTION = 66;
  int VAR = 67;
  int ONCLIPEVENT = 68;
  int ON = 69;
  int IDENTIFIER = 70;
  int LETTER = 71;
  int DIGIT = 72;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<BOOLEAN_LITERAL>",
    "\"null\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<DOUBLE_QUOTE>",
    "<SINGLE_QUOTE>",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"~\"",
    "\"<<\"",
    "\">>>\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"in\"",
    "\"break\"",
    "\"continue\"",
    "\"delete\"",
    "\"instanceof\"",
    "\"return\"",
    "\"with\"",
    "\"new\"",
    "\"function\"",
    "\"var\"",
    "\"onClipEvent\"",
    "\"on\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
  };

}
